
Hallo und herzlich willkommen auf der Gulaschprogrammiernacht, einer
Veranstaltung mit Technik, leckerem Essen und vielen großartigen
Menschen. Die folgenden Tipps wollen ein Leitfaden zum Umgang mit
diesen sein, um zwischenmenschliche Probleme zu vermeiden und eine
tolle GPN für alle zu ermöglichen.



* Allgemeines
- Behandle andere Leute möglichst so, wie sie behandelt werden möchten
- Wenn du dir unsicher bist, frag höflich
- Wenn jemand gemein ist, versucht, darüber zu reden
- Wenn es unangenehm wird, oder du Hilfe brauchst, wende dich an
  unsere Vertrauensleute (119)


**  Wow, ganz schön viele Leute hier
- Jep, letztes Jahr waren es etwa <Zahl> und die GPN wächst weiter

** Sind das alles Nerds?
- Manche wollen sich das ganze auch einfach nur anschauen. Vielleicht
  sind ein paar davon ja auch welche von uns und wissen es nur noch
  nicht ;-)

** OK, aber was ist mit...?
- Zu einigen Gruppen findest du im folgenden weitere
  Informationen. Read on.

* Mädchen und Frauen
- Wow, hier sind ja Mädels! Die sind doch bestimmt mit ihrem Freund /
  Mann da, oder? Und wenn nicht, kann ich sie angraben? Ich könnte
  nämlich ne Freundin gebrauchen...

> Leider ist der Frauenanteil in der Informatik und in technischen
  Bereichen allgemein ziemlich gering. Zwar gibt es hier einige
  Versuche, gegenzusteuern, aber viele empfinden nach wie vor das
  Umfeld äußerst unangenehm und bleiben nicht lange dabei. Bitte sei
  nicht der Grund dafür.

** Do's
- Behandle Mädchen und Frauen mit Respekt und Höflichkeit. Viele davon
  haben schon miese Erfahrungen gemacht und leider ist auch das Chaos
  in dieser Hinsicht nicht immer besonders fortschrittlich
- Frag nach Projekten, Spaces und Interessen, genau wie bei anderen
  Leuten auch
** Don'ts
- Es mag sich seltsam anhören, aber angegraben werden kann echt
  nerven. Vor allem auf Veranstaltungen mit >80% Jungs, die alle auf
  diese Idee kommen und von denen einige auch noch glauben, den Geist
  der Begehrten durch irgendwelche "Pickup"-Techniken hacken zu
  können. Wenn die Situation nicht gerade eindeutig auf Flirten
  hinausläuft (z.B. ihr hockt im Sonnenschein, trinkt Mate, habt euch
  schon ein paar Mal gegenseitig angegrinst, werdet gelegentlich rot
  dabei), lass es lieber sein. Du versaust ihr den Tag damit.
- Genauso schlimm, ist es, ständig in die Mädchenrolle gedrängt zu
  werden. Die Klassiker sind hier: "Bist du mit deinem Freund hier?
  -Was außerdem unter gruseliges Flirten fällt- oder "Was machst denn
  DU hier?". Es ist absolut mies wenn auf einer Chaosveranstaltung
  ständig in dieser Weise an der eigenen Technikkompetenz gezweifelt
  wird und es frustriert viele junge Haecksen endlos.
- Auf der anderen Seite stresst es auch, ständig am männlichen Maßstab
  gemessen zu werden und das Gefühl zu bekommen, nichts gegen eklige,
  pubertäre, verstörende oder sexistische Scheiße sagen zu dürfen,
  ohne den Status als cooles Mädchen zu verlieren. Ein klein bisschen
  Anstand und Höflichkeit wirken hier Wunder.
- Nicht jede von uns ist Feministin, Expertin für Frauenprobleme oder
  eine Koryphäe des Sozialen. Es nervt, sich für andere Frauen
  rechtfertigen zu müssen, zur Analytikerin der Frauenpsyche erklärt
  zu werden oder den modernen Feminismus gegen einen
  wikipediaerfahrenen Rethoriker verteidigen zu müssen. Wir sind zum
  Hacken und für nette Leute hier, lasst den anderen Kram in Ruhe,
  außer wir zeigen deutliches Interesse daran.


* Neurodivergente
- Ein paar Leute hier sind ... irgendwie seltsam. Sie schauen
  z.B. beim Reden weg, schnippen mit den Fingern oder wiegen sich hin
  und her und scheinen das lustig zu finden. Außerdem habe ich das
  Gefühl, dass in Gesprächen irgendwie keine richtige Verbindung
  aufkommt. Was ist da los?

> Neurodivergenz ist ein weites Feld und bei weitem noch nicht
vollständig erforscht. Viele Neurodivergente leiden darunter, dass ihr
Umfeld nicht mit ihnen klarkommt oder sie zwanghaft in Stereotypen
pressen will. Dabei würde es auch neurotypischen Menschen (also solche
die nicht neurodivergent sind) helfen, sich mit dieser Andersartigkeit
auseinander zu setzen und die eigenen Vorstellungen zu reflektieren

** Do's
- Auch Neurodivergente sind vorrangig hier um Spaß am Gerät zu haben
  und nette Leute zu treffen. Behandle sie also am besten so, dass sie
  sich als Teil des Ganzen fühlen können - ohne Bevormundung und
  Ausgrenzung.
- Höfliche und freundliche Nachfragen nach Besonderheiten (wie die
  Sache mit dem Fingerschnippen) werden oft bereitwillig
  beantwortet. Hier ist aber Fingerspitzengefühl gefragt.

** Don'ts
- Niemand mag nur auf einen Aspekt seines Seins reduziert werden. Also
  lass den Leuten auch Raum, eine Person zu sein und reduziere sie
  nicht auf ihre Andersartigkeit.
- Bevormundung fühlt sich unglaublich widerlich an, also tu das nicht.
- Bestehe nicht darauf, dass sich alle Neurodivergente wie
  Autisten/Asperger verhalten, auch wenn du solche Menschen
  kennst. Sei vor allem vorsichtig, wenn deine Erfahrung nur aus
  Filmen oder Wikipediaartikeln kommt.
- Diagnosen sind ganz dünnes Eis. Niemand braucht eine offizielle
  Diagnose um anders zu sein und oftmals wird durch das medizinische
  Establishment sehr viel Schaden angerichtet. Sie hier vorsichtig und
  lass den Leuten auch Raum für Wut auf eine neuronormalitätsfixierte
  Gesellschaft, ohne dich gleich angegriffen zu fühlen.


* Ausländer und Menschen mit Migrationshintergrund
- Hey, hier sind Leute, die aussehen als ob sie von weit weg
herkämen. Soll ich Ihnen erklären, wie Deutschland so ist?

> Moderne Migrationsbewegungen führen zu vielfältiger Herkunft, auch
bei Nerds. Diejenigen davon, die auf die GPN kommen wollen
wahrscheinlich vor allem freundliche Menschen treffen und mit
spannender Technik spielen. Die Kommunikation kann im Einzelfall
Probleme machen, aber Kosmopolitismus ist zum Glück eine weit
verbreitete Eigenschaft der Gemeinschaft.

** Do's
- Sei freundlich und hilf Leuten gegebenenfalls beim Übersetzen. Im
  Zweifel sind klare Aussagen in drei Sprachen gleichzeitig und mit
  Gesten unterlegt meist besser als grammatikalisch und
  artikulatorisch elaboriertes Englisch.
- Wenn es sich ergibt sind Gespräche über verschiedene Kulturen und
  Lebensweisen oft beiderseitig bereichernd.
** Don'ts 
- Stereotype können sehr schmerzhaft sein. Sei dir dessen bewusst und
  reduziere Leute nicht darauf. Auch vermeintlich positive Stereotype
  wie die vermeintlich asiatische Begabung für Mathematik können weh
  tun. Lass das also.

* Trans*
- Hier sind Leute bei denen ich mir nicht sicher bin, ob sie Männchen
  oder Weibchen sind. Und ein paar sehen eindeutig aus, tragen aber
  diese Pronomenschilder und da steht was anderes drauf. Das ist nur
  Spaß, oder?
> Geschlecht ist sozial konstruiert und wird zunehmend in Frage
  gestellt. Zunehmend mehr Menschen entdecken, dass sie als das
  andere, als ein drittes Geschlecht, ohne Geschlecht, oder mit
  wechselndem Geschlecht, weit schmerzfreier leben können, andere
  experimentieren mit diesen Ausdrucksformen.
** Do's
- Respektiere Pronomen, Namen und Identitäten. Niemand ist
  verpflichtet dir irgendwas zu beweisen. Wenn du damit absolut nicht
  klarkommst, lass diese Leute in Ruhe und nimm dir gegebenenfalls
  Zeit zu überlegen, warum es dir so wichtig ist, dass sie sich an
  diese Regeln halten.
** Don'ts
- Erschlage Leute nicht mit Stereotypen über Crossdresser,
  Dragqueens/kings und tausend anderen Identitäten zu denen irgendein
  Medienunternehmen fragwürdige Dokus dreht. 
- Egal was du gehört hast: Es ist heute nicht "ganz einfach und total
  problemlos" abseits der ab Geburt übergestülpten Geschlechterrollen
  zu leben und braucht weit mehr als "einen Termin beim
  Psychater". Bitte stell deine Fernsehsozialisierung hier nicht über
  die Lebenserfahrungen von Leuten.
- Manche genderabweichenden Menschen mögen schrille Klischees und
  genießen das ein oder andere anzügliche Kompliment. Andere nehmen
  sowas extrem persönlich. Wenn du den Unterschied nicht eindeutig
  sehen kannst, halte dich diesbeszüglich lieber zurück.
- Bitte erkläre Leuten nicht, auf welche Toiletten sie gehen oder
  nicht gehen können. Falls es hier zu irgendwelchen Problem kommt
  (wie z.B. Leuten die Spaß daran haben, solche Regeln wörtlich
  auszulegen um Mädchen/Frauen zu belästigen), wende dich bitte an
  uns.





* Kinder
- Wow hier sind ja wirklich kleine Menschen. Haben die sich verlaufen?

> Die GPN zieht Menschen aller Altersklassen an. Außerdem versuchen
diverse Initiativen wie z.B. Chaos macht Schule auch die Jugend zu
vernünftiger Medienkompetenz zu erziehen.

** Do's
- Du bist älter, sei ein Vorbild.
- Wenn sich die Kleinen für dein Projekt interessieren, erklär
  es. Benutz dafür altersangemessene Begriffe und wiederhole wichtige
  Informationen
- Viele Kinder sind noch nicht völlig verzogen und gehen weg, wenn sie
  sich langweilen oder nichts zu tun haben. Mach dir nichts daraus.
- Versuch dich zurück zu erinnern. Was würdest du dir als Kind in der
  Situation von der älteren Person wünschen, was davon wäre nach
  heutiger Maßgabe sinnvoll? Sei diese Person.


** Don'ts
- Bitte sei weder ein fies, noch bevormundend. Wenn du deine Ruhe
  brauchst, sag das höflich. Auch kleine Menschen haben Gefühle.
- Bitte streite dich nicht mit Zwergen. Ruf lieber uns, wir klären
  das.


* Diese Regeln sind voll doof und stören meine individuelle Freiheit, was würde passieren, wenn ich aus Trotz folgendes subversive Kunstwerk auf die Wände der HFG sprühen würde: Ein in leuchtenden Farben gestalter, 3 meter hoher, anatomisch korekter...
Auf dich hab' ich gewartet. Make my day, punk. Nein ernsthaft: Wir
finden es auch blöd, dass wir überhaupt Leitlinien brauchen, aber
leider gab es immer wieder Vorfälle und zu viele neue Leute um sich
noch auf einen allgemeinen Hackerkonsens zu berufen. Daher machen wir
die Regeln vorher explizit. Wenn du mit uns darüber streiten magst,
ruf uns an. Am besten fragst du nach Lisa, die hat auch diesen Flyer
verbrochen.





